### ISSUE TITLE
Instalacion

### ISSUE THREAD

**Issue by leamormo** [josiasmc/facturador-electronico-cr#1]
Existe alguna guía de instalación de del componente, me parece excelente y me gustaría probarlo

**Comment by cristophermr** [comment]
Buenos días, 

Adjunto comentarios del creador de la libreria.

Para inicializar la db, y para migraciones, se hace así:
Storage::run_migrations($db);

Para usarlo, se inicializa la clase así:
//ajustes disponibles
$settings = [
            'crypto_key' => '',
            'storage_path' => '', //ruta completa en donde guardar los comprobantes
            'callback_url' => ''
        ];

$facturador = new FacturadorElectronico($db, $settings); //$db es un objeto mysqli. El segundo parametro es opcional


Y en cuanto a que se puede hacer con el objeto $facturador creado, puedes revisar el archivo FacturadorElectronico.php, donde están todos los métodos, y descripciones de lo que hace.


Antes de poder enviar comprobantes de un emisor, hay que registrarlo así:
$datos_de_empresa = [
'cedula' => '509990999',
'ambiente' => '1',//1 prod, 2 stag
'usuario' => 'usuario_mh',
'contra' => 'contra_mh',
'pin' => 'pin_llave',
'llave_criptografica' => contenido del archivo .pem
];
$id_empresa = $facturador->guardarEmpresa($datos_de_empresa);

Para crear un comprobante, y ponerlo en la cola de envío, lo haces así:
//Un array estructurado de acuerdo a la estructura del xml. Este es para v4.2. La clave es autogenerada si no se envia
$datos = [
    'NumeroConsecutivo' => '00100001010000000013',
    'FechaEmision' => date('c'),
    'Emisor' => [
        'Nombre' => 'Razon Social',
        'Identificacion' => [
            'Tipo' => '01',
            'Numero' => '609990999'
        ],
        'Ubicacion' => [
            'Provincia' => '6',
            'Canton' => '08',
            'Distrito' => '01',
            'OtrasSenas' => 'direccion'
        ],
        'CorreoElectronico' => 'correo@email.com'
    ],
    'Receptor' => [
        'Nombre' => 'Razon Social',
        'Identificacion' => [
            'Tipo' => '01',
            'Numero' => '609990999'
        ],
        'Ubicacion' => [
            'Provincia' => '6',
            'Canton' => '08',
            'Distrito' => '01',
            'OtrasSenas' => 'direccion'
        ],
        'CorreoElectronico' => 'correo@gmail.com'
    ],
    'CondicionVenta' => '01',
    'MedioPago' => '01',
    'DetalleServicio' => [
        'LineaDetalle' => [
            [
            'NumeroLinea' => '1',
            'Codigo' => [
                'Tipo' => '04',
                'Codigo' => '010001'
            ],
            'Cantidad' => '1',
            'UnidadMedida' => 'Os',
            'Detalle'  => 'Servicio de programacion',
            'PrecioUnitario' => '15000.00',
            'MontoTotal' => '15000.00',
            'SubTotal' => '15000.00',
            'MontoTotalLinea' => '15000.00'
            ],
            [
            'NumeroLinea' => '2',
            'Codigo' => [
                'Tipo' => '04',
                'Codigo' => '010010'
            ],
            'Cantidad' => '2',
            'UnidadMedida' => 'h',
            'Detalle'  => 'Servicio al cliente',
            'PrecioUnitario' => '1000.00',
            'MontoTotal' => '2000.00',
            'SubTotal' => '2000.00',
            'MontoTotalLinea' => '2000.00'
            ]
        ]
        ],
    'ResumenFactura' => [
        'TotalServExentos' => '17000.00',
        'TotalExento' => '17000.00',
        'TotalVenta' => '17000.00',
        'TotalVentaNeta' => '17000.00',
        'TotalComprobante' => '17000.00'
    ]
];
$clave = $facturador->enviarComprobante($datos, $id_empresa);

//para enviar la cola
$docs_enviados = $facturador->enviarCola();

**Comment by josiasmc** [comment]
Ya se actualizó el README con los datos actuales de uso.
