### ISSUE TITLE
Recepción de Documentos 

### ISSUE THREAD

**Issue by jarscr** [josiasmc/facturador-electronico-cr#4]
Hola, no tiene claro como funciona recepcionar documentos.

Intente esto
$comprobante = [
    'Clave' => '50625082100020123045601200001010000000024100000010'
    'NumeroConsecutivo' => '00500001050000000023'
    'Emisor'=> [
            Nombre => PEDRO PEREZ
            Identificacion => [
                (
                     Tipo => 01
                     Numero => 201230456
                )

        )
]

Siendo que:
* Clave es el documento que recibo, 
* Consecutivo es mi consecutivo receptor
* Emisor es quien me emite la facura.

Me faltan varios datos acá aun, que no lo veo en el codigo, no se si van en el arreglo.

Serian:
* monto Total De Gasto Aplicable
* monto Total Impuesto Acreditar
* condicion de Impuesto
* Codigo Actividad Receptor
* mensaje (Acepto, Acepto Parcial, Rechazo)

No se si esta parte es completa o no. Quiero actualizar el codigo del proyecto, pues hace mucho no se hacen mejoras, y Recepcion esta sin documentacion en el proyecto

Saludos

**Comment by JeanPaulCE** [comment]
se que ah pasado tiempo pero quiza ah alguien le sirva, hay que prosesar la cola.
la funcion de recepcionar solo añade a cola el comprobante no lo envia y si lo haces en dos peticiones separadas
obiamente por como funciona php(sin persistencia entre peticiones exepto por variables especiales) perderas la creacion anteriro. 

try {
            $this->facturador->recepcionar($xml_decodificado,$mensajeAceptacion,$this->setings->getIdEmpresa());
             $this->facturador->enviarCola();
     
        } catch (\Throwable $th) {
            
        }

**Comment by josiasmc** [comment]
La cola se guarda en la base de datos, por lo que la función de enviarCola envía todo desde la última vez que se llamó, enviando todos los documentos procesados en el tiempo desde la última invocación.
